"""create orders table

Revision ID: 9c2dbd5bfa98
Revises: 2b306a96c436
Create Date: 2019-12-06 00:53:34.896768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2dbd5bfa98'
down_revision = '2b306a96c436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'plant_culture', ['status'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
