"""create orders table

Revision ID: e3b3df2f2ce7
Revises: 5e5b5f215354
Create Date: 2019-12-06 01:04:22.897878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b3df2f2ce7'
down_revision = '5e5b5f215354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'orders', 'plant_culture', ['status'], ['id'])
    op.drop_column('orders', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    # ### end Alembic commands ###
